import {
  getIsoWeekId,
  type WeeklySummary,
  type WeeklySummaryGenerator,
} from '../storage/weekly-summary.js';

interface SlackHeaderBlock {
  readonly type: 'header';
  readonly text: { readonly type: 'plain_text'; readonly text: string };
}

interface SlackSectionBlock {
  readonly type: 'section';
  readonly fields: ReadonlyArray<{ readonly type: 'mrkdwn'; readonly text: string }>;
}

interface SlackDividerBlock {
  readonly type: 'divider';
}

interface SlackContextBlock {
  readonly type: 'context';
  readonly elements: ReadonlyArray<{ readonly type: 'mrkdwn'; readonly text: string }>;
}

type SlackBlock = SlackHeaderBlock | SlackSectionBlock | SlackDividerBlock | SlackContextBlock;

export type SlackBlockKitPayload = {
  readonly blocks: readonly SlackBlock[];
};

export interface DigestPreview {
  readonly week: string;
  readonly payload: SlackBlockKitPayload;
  readonly text: string;
}

function stripMrkdwn(text: string): string {
  return text
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/_([^_]+)_/g, '$1');
}

/** Plain-text rendering of a Block Kit digest, derived from the same payload Slack receives. */
export function renderDigestPlainText(payload: SlackBlockKitPayload): string {
  const parts: string[] = [];
  for (const block of payload.blocks) {
    switch (block.type) {
      case 'header':
        parts.push(block.text.text);
        break;
      case 'section':
        parts.push(block.fields.map((field) => stripMrkdwn(field.text)).join('\n\n'));
        break;
      case 'divider':
        parts.push('---');
        break;
      case 'context':
        parts.push(block.elements.map((el) => stripMrkdwn(el.text)).join('\n'));
        break;
    }
  }
  return parts.join('\n\n');
}

export function buildDigestContent(summary: WeeklySummary): {
  readonly payload: SlackBlockKitPayload;
  readonly text: string;
} {
  const payload = formatSlackDigest(summary);
  return { payload, text: renderDigestPlainText(payload) };
}

/** Same week + Block Kit payload the send path posts, plus a plain-text rendering. */
export function buildCurrentWeekDigest(generator: WeeklySummaryGenerator): DigestPreview {
  const week = getIsoWeekId(new Date());
  const summary = generator.generate(week);
  return { week, ...buildDigestContent(summary) };
}

export function formatSlackDigest(summary: WeeklySummary): SlackBlockKitPayload {
  const totalCost = summary.totalCostUsd?.toFixed(4) ?? '—';
  const avgEfficiency =
    summary.avgEfficiencyScore != null ? (summary.avgEfficiencyScore * 100).toFixed(1) : '—';
  const topAntiPatternEntry = Object.entries(summary.antiPatternCounts ?? {}).sort(
    ([, a], [, b]) => b - a,
  )[0];
  const topAntiPattern = topAntiPatternEntry ? topAntiPatternEntry[0] : 'none';
  const safeTopAntiPattern = topAntiPattern.replace(/[\`\n]/g, '_');

  const blocks: SlackBlock[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: '🤖 Weekly AI Coding Summary' },
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Total Cost:*\n$${totalCost}` },
        { type: 'mrkdwn', text: `*Avg Efficiency:*\n${avgEfficiency}/100` },
        { type: 'mrkdwn', text: `*Sessions:*\n${summary.sessionCount}` },
        { type: 'mrkdwn', text: `*Top Anti-pattern:*\n\`${safeTopAntiPattern}\`` },
      ],
    },
  ];

  // Read defensively — summaries persisted to disk before this field existed
  // won't have it, same as this file's existing antiPatternCounts fallback.
  const platforms = Object.entries(summary.perPlatform ?? {});
  if (platforms.length > 1) {
    blocks.push({
      type: 'section',
      fields: platforms.map(([platform, stats]) => {
        const eff =
          stats.avgEfficiencyScore != null ? (stats.avgEfficiencyScore * 100).toFixed(1) : '—';
        return {
          type: 'mrkdwn' as const,
          text: `*${platform}:*\n${stats.sessionCount} sessions, ${eff}/100 efficiency`,
        };
      }),
    });

    const visibilityLevels = new Set(platforms.map(([, stats]) => stats.visibilityLevel));
    if (visibilityLevels.size > 1) {
      blocks.push({
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: '_These platforms have different instrumentation coverage — differences above may reflect what each platform lets Preflight observe, not actual developer behavior._',
          },
        ],
      });
    }
  }

  blocks.push(
    { type: 'divider' },
    {
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: '_Generated by Preflight_',
        },
      ],
    },
  );

  return { blocks };
}
